Repository GSG-CF05/Team1-Sanajib-LaunchToSpace, pull requests merged in 2022-03, with the labels that each got.

#23 I added the readme file that contains all projects details
  README.md
Labels: in-progress

#25 create navbar html, css
  CSS/index.css
  images/logo.svg
  index.html
Labels: approved

#28 add content to first page and style it
  CSS/font/SpaceQuest-Xj4o.ttf
  CSS/index.css
  index.html
Labels: approved

#29 add navbar to second page
  CSS/launches.css
  HTML/launches.html
Labels: approved

#31 30 fixed navbar links
  HTML/launches.html
  index.html
Labels: approved

#34 format the code and fix the space between content
  CSS/index.css
  index.html
Labels: approved

#38 Fix alive link bug
  CSS/index.css
  CSS/launches.css
  HTML/about.html
  HTML/launches.html
  HTML/pod.html
  index.html
Labels: approved

#39 Fix first page index.html
  HTML/launches.html
  index.html
Labels: approved

#40 6 add html structure to latest launch
  CSS/launches.css
  HTML/launches.html
  images/RR8JLzm.png
Labels: approved

#43 I modified the css of the upcoming launch section, increased the heig…
  CSS/launches.css
Labels: for-review

#44 create HTML structure for the all launches section and style it
  CSS/launches.css
  HTML/launches.html
Labels: approved

#47 8 add functionality to latest launch
  CSS/launches.css
  HTML/launches.html
  JS/launches.js
Labels: approved

#48 11 add timer
  CSS/launches.css
  HTML/launches.html
  JS/launches.js
Labels: approved

#52 add navbar to pod page html and css
  CSS/pod.css
  HTML/pod.html
Labels: approved

#54 create the html structure of welcome section in pod page
  CSS/pod.css
  HTML/pod.html
Labels: 30-min, done

#55 create the html structure for picture of the day section
  CSS/pod.css
  HTML/pod.html
Labels: approved

#51 add sponsors section and the footer to launches page,
  CSS/launches.css
  HTML/launches.html
  images/footer-image1.png
  images/footer-image2.png
  images/sponsor.png
Labels: approved

#60 edit heading in pod page
  HTML/pod.html
Labels: approved, done

#61 add footer to third page
  CSS/pod.css
  HTML/pod.html
Labels: for-review

#62 Add footer 3ed page and about page
  .vscode/settings.json
  CSS/about.css
  CSS/pod.css
  HTML/about.html
  HTML/pod.html
  JS/song.js
  images/mebmer3.jpg
  images/member1.jpg
  images/member2.jpeg
  images/member4.jpg
  index.html
Labels: for-review
